name: Generate and deploy documentation
run-name: ${{ github.actor }} is generating and deploying documentation

on:
  push:
    branches: [ main ]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        shell: bash

      - name: Configure the project
        uses: threeal/cmake-action@v1.2.0

      - name: Generate project documentation
        run: cmake --build build --target docs -- -j$(nproc)

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen
